### ISSUE TITLE
Support ELK v5.0.0

### ISSUE THREAD

**Issue by arpit-nagar** [gigi81/elk-windows-installer#1]
Thanks for super easy utility.
Kibana released a new version 5.0
Can you please update installer to support it.

**Comment by gigi81** [comment]
Hi @arpit-nagar 
Here is a un-tested build with all latest versions (5.0.0):
https://ci.appveyor.com/project/gigi81/elk-windows-installer/build/artifacts

You are welcome to try it out. Let me know how it goes. I will have at look at it myself in a week or so.

**Comment by gigi81** [comment]
Actually, try this one:
https://ci.appveyor.com/api/buildjobs/7t3f7lxis31f087a/artifacts/dist%2Felk-x64-1.0.20.exe

already found and fixed some issues due to changes in 5.x

**Comment by Phlogi** [comment]
@gigi81 Thanks, this worked for me well so far. How would the update process look like to keep config data and database entries?

**Comment by arpit-nagar** [comment]
works for me as well so far 👍

**Comment by gigi81** [comment]
@Phlogi this installer is not designed for upgrading. my suggestion would be to:
- backup elasticsearch data folder and your custom logstash configuration (if any)
- uninstall old version
- install new one
- stop elk services
- copy back elasticsearch data and logstash configuration back
- start elasticsearch service only
- wait for the data upgrade to complete (read official elastic documentation on this. it might not be that straight forward)
- start the other elk services

If you try this, let us know how it goes!

**Comment by Dvi23** [comment]
hey guys love the work !!! really appreciate all the time and effort invested here...i need to use the csv function in the new version of kibana ....can i ask for a upgrade to the installer please to 5.4.3

**Comment by gigi81** [comment]
Installer upgraded to 5.5.5
Closing the ticket.
