### ISSUE TITLE
elk-windows-installer-1.0.16 解压包版本 执行build.bat不成功

### ISSUE THREAD

**Issue by Thinkgamer** [gigi81/elk-windows-installer#2]
下载elk-windows-installer-1.0.16.tar.gz 解压执行build.bat 报错：
File: failed opening file "temp\kibana\node_modules\jade\node_modules\uglify-js\node_modules\yargs\node_modules\cliui\node_modules\center-align\node_modules\align-text\node_modules\kind-of\package.json"
Error in script "elk.nsi" on line 237 -- aborting creation process

猜想是目录层次太深导致的

**Comment by gigi81** [comment]
Hi, from the release folder you should download the exe not the tar.gz
The tar.gz are the source files. If you need the source files you can download them using git.
